<?php

namespace MSIM\ClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChoseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoseRepository extends EntityRepository
{
}
